// Admin Authentication Manager
// Handles Cognito OAuth, JWT token storage, and protected route access

const AdminAuth = {
  // Values are injected from admin-config.js (generated by setup.sh)
  get clientId() { return (typeof ADMIN_CONFIG !== 'undefined' && ADMIN_CONFIG.cognitoClientId) || ''; },
  get redirectUri() { return (typeof ADMIN_CONFIG !== 'undefined' && ADMIN_CONFIG.callbackUrl) || ''; },
  get cognitoDomain() { return (typeof ADMIN_CONFIG !== 'undefined' && ADMIN_CONFIG.cognitoDomain) || ''; },
  get apiEndpoint() { return (typeof ADMIN_CONFIG !== 'undefined' && ADMIN_CONFIG.apiEndpoint) || '/admin/api'; },
  responseType: 'code',
  scope: 'openid email profile',

  get devMode() { return typeof ADMIN_CONFIG !== 'undefined' && ADMIN_CONFIG.devMode === true; },

  // Initialize auth on page load
  init() {
    const path = window.location.pathname;
    const token = this.getToken();

    // Dev mode: skip all auth checks, show placeholder user
    if (this.devMode) {
      if (!path.includes('/admin/index.html') && path !== '/admin/') {
        this.setupAdminPage('preview@serenityspa.com');
      }
      return;
    }

    // Login page: check if already authenticated
    if (path.includes('/admin/index.html') || path === '/admin/') {
      if (token && this.isTokenValid(token)) {
        window.location.href = './dashboard.html';
      }
      this.setupLoginPage();
    }
    // Protected pages: redirect to login if no token
    else if (path.includes('/admin/')) {
      if (!token || !this.isTokenValid(token)) {
        window.location.href = './index.html';
      } else {
        this.setupAdminPage();
      }
    }
  },

  // Get stored JWT token
  getToken() {
    return localStorage.getItem('admin_token');
  },

  // Store JWT token
  setToken(token) {
    localStorage.setItem('admin_token', token);
  },

  // Check if token is valid (basic expiry check)
  isTokenValid(token) {
    if (!token) return false;

    try {
      const payload = JSON.parse(atob(token.split('.')[1]));
      const expiry = payload.exp * 1000; // Convert to milliseconds
      return Date.now() < expiry;
    } catch (e) {
      return false;
    }
  },

  // Decode JWT to get user info
  getUserInfo() {
    const token = this.getToken();
    if (!token) return null;

    try {
      return JSON.parse(atob(token.split('.')[1]));
    } catch (e) {
      return null;
    }
  },

  // Setup login page
  setupLoginPage() {
    const googleBtn = document.getElementById('google-signin-btn');
    const messageEl = document.getElementById('auth-message');

    if (googleBtn) {
      googleBtn.addEventListener('click', () => {
        this.initiateGoogleOAuth();
      });
    }

    // Check for auth callback
    this.handleAuthCallback();
  },

  // Setup admin pages (display user email, logout)
  setupAdminPage(devEmail = null) {
    const userInfo = this.getUserInfo();
    const userEmailEl = document.getElementById('user-email');
    const logoutBtn = document.getElementById('logout-btn');

    if (userEmailEl) {
      userEmailEl.textContent = devEmail || userInfo?.email || 'Admin User';
    }

    if (logoutBtn) {
      logoutBtn.addEventListener('click', () => {
        if (this.devMode) return;
        this.logout();
      });
    }
  },

  // Initiate Google OAuth flow
  initiateGoogleOAuth() {
    const params = new URLSearchParams({
      client_id: this.clientId,
      redirect_uri: this.redirectUri,
      response_type: this.responseType,
      scope: this.scope,
      identity_provider: 'Google'
    });

    window.location.href = `https://${this.cognitoDomain}/oauth2/authorize?${params.toString()}`;
  },

  // Handle OAuth callback (authorization code)
  handleAuthCallback() {
    const params = new URLSearchParams(window.location.search);
    const code = params.get('code');
    const messageEl = document.getElementById('auth-message');

    if (code) {
      this.exchangeCodeForToken(code, messageEl);
    }
  },

  // Exchange authorization code for JWT token
  async exchangeCodeForToken(code, messageEl) {
    try {
      if (messageEl) {
        messageEl.textContent = 'Authenticating...';
        messageEl.className = 'auth-message';
      }

      const tokenUrl = `https://${this.cognitoDomain}/oauth2/token`;
      const params = new URLSearchParams({
        grant_type: 'authorization_code',
        client_id: this.clientId,
        redirect_uri: this.redirectUri,
        code
      });

      const response = await fetch(tokenUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: params.toString()
      });

      if (!response.ok) {
        throw new Error('Token exchange failed');
      }

      const data = await response.json();
      this.setToken(data.id_token);

      if (messageEl) {
        messageEl.textContent = 'Sign in successful. Redirecting...';
        messageEl.className = 'auth-message success';
      }

      setTimeout(() => {
        window.location.href = './dashboard.html';
      }, 1000);
    } catch (error) {
      console.error('Auth error:', error);
      if (messageEl) {
        messageEl.textContent = 'Sign in failed. Please try again.';
        messageEl.className = 'auth-message error';
      }
    }
  },

  // Logout
  logout() {
    localStorage.removeItem('admin_token');
    window.location.href = './index.html';
  },

  // Make authenticated API request
  async request(path, options = {}) {
    const token = this.getToken();

    if (!token || !this.isTokenValid(token)) {
      window.location.href = './index.html';
      return null;
    }

    const headers = {
      'Authorization': `Bearer ${token}`,
      'Content-Type': 'application/json',
      ...options.headers
    };

    // Resolve full URL against API endpoint
    const url = path.startsWith('http') ? path : `${this.apiEndpoint}${path.replace('/admin/api', '')}`;

    try {
      const response = await fetch(url, {
        ...options,
        headers
      });

      if (response.status === 401) {
        // Token expired
        this.logout();
        return null;
      }

      return response;
    } catch (error) {
      console.error('Request failed:', error);
      throw error;
    }
  }
};

// Initialize on page load
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', () => AdminAuth.init());
} else {
  AdminAuth.init();
}
