// Admin Panel Configuration
// This file is auto-generated by setup.sh after running the deployment.
// Do not edit manually — re-run setup.sh to update.

const ADMIN_CONFIG = {
  apiEndpoint: '',      // API Gateway URL — set by setup.sh
  cognitoClientId: '',  // Cognito App Client ID — set by setup.sh
  cognitoDomain: '',    // Cognito Hosted UI domain — set by setup.sh
  callbackUrl: '',      // OAuth redirect URL — set by setup.sh
  devMode: true         // Set to false when Cognito is configured
};
