// Admin Panel Configuration
// This file is auto-generated by setup.sh after running the deployment.
// Do not edit manually — re-run setup.sh to update.

const ADMIN_CONFIG = {
  apiEndpoint: '',
  cognitoClientId: '58up8qkeao4ucfctbevhfok9fs',
  cognitoDomain: 'serenity-spa-admin.auth.us-west-2.amazoncognito.com',
  callbackUrl: 'https://d3otg5fszt3roj.cloudfront.net/admin/index.html',
  devMode: false
};
